version: "3.7"
networks:
  dev:

services:
  db:
    image: postgres:15
    container_name: db_app
    env_file:
      - fastApiProject1/.env-non-dev
    networks:
      - dev

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build:
      context: fastApiProject1
    container_name: fastapi_app
    env_file:
      - fastApiProject1/.env-non-dev
    command: ["/fastapi_app/docker/app.sh"]
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - dev

  frontend:
    build:
      context: frontrent
    container_name: react_app
    networks:
      - dev